seed: 1
mode: 'sr_only'
network: 'SpatialRectifier'
pre_train: False
bs: 1
lr: 1.e-4
epochs: 20
shuffle: True
augment: False

save_model_interval: 1000
tb_log_interval: 100
imsize: [240, 320]
loss: 'SRLoss'

# if you wanna train from scratch, please set off this key: init_train
sr_checkpoint_path: '/home/yukisaito/TiltedDepthEstimation/results/sr_only/models/iter_58000.p'
checkpoint_path: 
init_train: True

dataset: 'OurDataset'
train_dataset: './data/my_scannet_standard_train_test_val_split.pkl'
test_dataset: './data/my_scannet_standard_train_test_val_split.pkl'
