seed: 1
mode: 'sr_depth_net'
network: 'SpatialRectifierResnetUnet'
pre_train: False
bs: 32
lr: 1.e-5
epochs: 50
shuffle: True
augment: False

save_model_interval: 5000
tb_log_interval: 1000
imsize: [240, 320]
loss: 'SRDenseDepthFullLoss'
input_augmentation: 'no_warp' #'random_warp_input' 
image_padding_mode: 'mean' #  mean 'border' #'reflection'

# if you wanna train from scratch, please set off this key: init_train
sr_checkpoint_path: '/home/yukisaito/TiltedDepthEstimation/results/sr_only_no_warp/models/model-best_full2dofa.pkl'
#'/home/yukisaito/TiltedDepthEstimation/results/sr_only/models/model-best_standard.pkl' #full2dofa.pkl' # iter_22000_standard

checkpoint_path: '/home/yukisaito/TiltedDepthEstimation/results/resnetunet/models/iter_15000.pkl'
init_train: False
start_epochs: 0
full_checkpoint_path: '/home/yukisaito/TiltedDepthEstimation/results/sr_resnetunet_full/models/model-best-scannet_full_standard_pitch:1.0_20220420_Ours.pkl'

# model-best-grav-aligned_standard.pkl'
#model-best-scannet_full_standard_roll:05_pitch:05_20220415.pkl'

#model-best-scannet_full_standard_roll:1.0_20220420_Ours.pkl'
#model-best-scannet_full_standard_roll:05_pitch:05_20220415.pkl'
#model-best-sr=12000_full2dofa-net=150000-full=30-lr=5e-5-scannet_full_standard.pkl'



dataset: 'scannet' #'TUMrgbd_frei1rpy'
train_dataset: './data/my_scannet_standard_train_test_val_split.pkl'
test_dataset: './data/my_scannet_standard_train_test_val_split.pkl' 
