seed: 1
mode: 'depth_net'
network: 'UnetPartialConv'
pre_train: True
bs: 32
lr: 1.e-4
epochs: 50
shuffle: True
augment: False

save_model_interval: 3000
tb_log_interval: 1000
imsize: [240, 320]
loss: 'DenseDepthLoss'
input_augmentation: 'random_warp_input'

# if you wanna train from scratch, please set off this key: init_train
sr_checkpoint_path:
checkpoint_path:
init_train: True

dataset: 'scannet'
train_dataset: './data/my_scannet_standard_train_test_val_split.pkl'
test_dataset: './data/my_scannet_standard_train_test_val_split.pkl'
